[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  # Environment variables jika diperlukan
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/mediafire"
  to = "/.netlify/functions/mediafire"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
